// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(Cloud9Context))]
    [Migration("20260127101620_UpdateBookingModel")]
    partial class UpdateBookingModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Persons")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TableId")
                        .HasColumnType("integer");

                    b.Property<int?>("TableId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.HasIndex("TableId1");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Appetizers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mains"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Wine"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Beer"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cocktails"
                        });
                });

            modelBuilder.Entity("backend.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("SpecialDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Toasted bread topped with fresh tomatoes, basil, and a drizzle of balsamic glaze.",
                            ImageUrl = "/images/bruschetta.jpg",
                            IsSpecial = false,
                            Name = "Bruschetta",
                            Price = 12m,
                            Tags = "Tomato | Basil | Balsamic glaze"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Succulent shrimp sautéed in garlic butter sauce, served with a side of crusty bread.",
                            ImageUrl = "/images/garlicshrimp.jpg",
                            IsSpecial = false,
                            Name = "Garlic shrimp",
                            Price = 14m,
                            Tags = "Shrimp | Garlic | Butter"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Mushroom caps stuffed with a savory mixture of cheese and herbs, baked to perfection.",
                            ImageUrl = "/images/stuffed_mushrooms.jpg",
                            IsSpecial = false,
                            Name = "Stuffed Mushrooms",
                            Price = 14m,
                            Tags = "Mushrooms | Cheese | Herbs"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Fresh mozzarella, ripe tomatoes, and basil leaves drizzled with olive oil and balsamic reduction.",
                            ImageUrl = "/images/caprese.jpg",
                            IsSpecial = false,
                            Name = "Caprese Salad",
                            Price = 11m,
                            Tags = "Mozzarella | Tomato | Basil"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Freshly grilled salmon served with a side of lemon and asparagus.",
                            ImageUrl = "/images/salmon.jpg",
                            IsSpecial = false,
                            Name = "Grilled Salmon",
                            Price = 25m,
                            Tags = "Salmon | Lemon | Asparagus"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Juicy ribeye steak cooked to perfection, topped with garlic butter and served with creamy mashed potatoes.",
                            ImageUrl = "/images/ribeye.jpg",
                            IsSpecial = true,
                            Name = "Ribeye Steak",
                            Price = 30m,
                            Tags = "Beef | Garlic Butter | Mashed Potatoes"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Classic cheesecake with a graham cracker crust, topped with fresh strawberry sauce.",
                            ImageUrl = "/images/cheesecake.jpg",
                            IsSpecial = false,
                            Name = "Cheesecake",
                            Price = 8m,
                            Tags = "Cream Cheese | Graham Cracker Crust | Strawberry Sauce"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Warm chocolate cake with a gooey center, served with vanilla ice cream and raspberry sauce.",
                            ImageUrl = "/images/lava_cake.jpg",
                            IsSpecial = false,
                            Name = "Chocolate Lava Cake",
                            Price = 9m,
                            Tags = "Dark Chocolate | Vanilla Ice Cream | Raspberry Sauce"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "A full-bodied red wine with rich flavors of dark fruit and a hint of spice.",
                            ImageUrl = "/images/shiraz.jpg",
                            IsSpecial = false,
                            Name = "Chapel Hill Shiraz",
                            Price = 56m,
                            Tags = "AU | Bottle"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "A robust red wine with notes of blackberry, plum, and a touch of oak.",
                            ImageUrl = "/images/malbee.jpg",
                            IsSpecial = false,
                            Name = "Catena Malbee",
                            Price = 59m,
                            Tags = "AU | Bottle"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "A crisp and refreshing rosé wine with flavors of strawberry and citrus.",
                            ImageUrl = "/images/rose.jpg",
                            IsSpecial = false,
                            Name = "La Vieille Rose",
                            Price = 44m,
                            Tags = "FR | 750 ml"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            Description = "A smooth and hoppy pale ale with notes of citrus and pine.",
                            ImageUrl = "/images/pale_ale.jpg",
                            IsSpecial = false,
                            Name = "Rhino Pale Ale",
                            Price = 31m,
                            Tags = "CA | 750 ml"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Description = "A classic Irish stout with a rich, creamy texture and flavors of roasted malt and coffee.",
                            ImageUrl = "/images/irish_guiness.jpg",
                            IsSpecial = false,
                            Name = "Irish Guinness",
                            Price = 26m,
                            Tags = "IE | 750 ml"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 6,
                            Description = "A refreshing cocktail made with Aperol, prosecco, and a splash of soda, garnished with an orange slice.",
                            ImageUrl = "/images/aperol.jpg",
                            IsSpecial = false,
                            Name = "Aperol Spritz",
                            Price = 20m,
                            Tags = "Aperol | Prosecco | soda | 30 ml"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            Description = "A classic cocktail made with dark rum and ginger beer, served over ice with a slice of lime.",
                            ImageUrl = "/images/dark_stormy.jpg",
                            IsSpecial = false,
                            Name = "Dark 'N' Stormy",
                            Price = 16m,
                            Tags = "Dark rum | Ginger beer | Slice of lime"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            Description = "A sweet and tangy cocktail made with rum, fresh strawberries, citrus juice, and a touch of sugar.",
                            ImageUrl = "/images/strawberry_daiquiri.jpg",
                            IsSpecial = false,
                            Name = "Strawberry Daiquiri",
                            Price = 10m,
                            Tags = "Rum | Citrus juice | Sugar"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            Description = "A timeless cocktail made with bourbon, brown sugar, and Angostura bitters, garnished with an orange twist.",
                            ImageUrl = "/images/old_fashioned.jpg",
                            IsSpecial = false,
                            Name = "Old Fashioned",
                            Price = 31m,
                            Tags = "Bourbon | Brown sugar | Angostura Bitters"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            Description = "A classic Italian cocktail made with gin, sweet vermouth, and Campari, garnished with an orange slice.",
                            ImageUrl = "/images/negroni.jpg",
                            IsSpecial = false,
                            Name = "Negroni",
                            Price = 26m,
                            Tags = "Gin | Vermouth | Campari | Orange garnish"
                        });
                });

            modelBuilder.Entity("backend.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 4,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 4,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 4,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 6,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 6,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 6,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 6,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 6,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 6,
                            IsAvailable = true
                        });
                });

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.HasOne("backend.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId");

                    b.HasOne("backend.Models.Table", null)
                        .WithMany("Bookings")
                        .HasForeignKey("TableId1");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("backend.Models.MenuItem", b =>
                {
                    b.HasOne("backend.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("backend.Models.Table", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
