// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(Cloud9Context))]
    partial class Cloud9ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Guests")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TableId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Appetizers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Main Courses"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cocktails"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Wine"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Beer"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Tasting Menu"
                        });
                });

            modelBuilder.Entity("backend.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("SpecialDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            IsSpecial = false,
                            Name = "Bruschetta",
                            Price = 89m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            IsSpecial = false,
                            Name = "Beef Carpaccio",
                            Price = 149m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            IsSpecial = true,
                            Name = "Ribeye Steak",
                            Price = 289m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            IsSpecial = false,
                            Name = "Spaghetti Carbonara",
                            Price = 179m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            IsSpecial = false,
                            Name = "Tiramisu",
                            Price = 95m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            IsSpecial = false,
                            Name = "Panna Cotta",
                            Price = 85m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            IsSpecial = false,
                            Name = "IPA Beer",
                            Price = 79m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 6,
                            IsSpecial = false,
                            Name = "Merlot Wine",
                            Price = 99m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            IsSpecial = false,
                            Name = "Old Fashioned Cocktail",
                            Price = 129m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            IsSpecial = false,
                            Name = "Gin & Tonic",
                            Price = 109m
                        });
                });

            modelBuilder.Entity("backend.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 4,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 4,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 4,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 6,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 6,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 6,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 6,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 6,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 6,
                            IsAvailable = true
                        });
                });

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.HasOne("backend.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("backend.Models.MenuItem", b =>
                {
                    b.HasOne("backend.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Navigation("MenuItems");
                });
#pragma warning restore 612, 618
        }
    }
}
